version: '3.8'

services:
  frontend:
    image: nginx:alpine
    container_name: friofacil-frontend
    restart: unless-stopped
    expose:
      - "80" # IMPORTANTE! Não usar "ports", deixar o Traefik cuidar.
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.friofacil.rule=Host(`usefriofacil.com.br`)"
      - "traefik.http.routers.friofacil.entrypoints=websecure"
      - "traefik.http.routers.friofacil.tls=true"
      - "traefik.http.routers.friofacil.tls.certresolver=letsencrypt"
      - "traefik.http.routers.friofacil.entrypoints=web,websecure"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.friofacil.middlewares=redirect-to-https"
      - "traefik.http.services.friofacil.loadbalancer.server.port=80"